name: msrv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "47 5 * * 6"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@1.48
      - name: Running test script
        run: |
          cargo update -p log --precise=0.4.18
          cargo update -p httpdate --precise=1.0.2
          cargo update -p serde_json --precise=1.0.100
          cargo update -p chrono --precise=0.4.23
          cargo update -p num-traits --precise=0.2.18
          cargo update -p tempfile --precise=3.17.1
          cargo update -p libc --precise=0.2.163
          cargo update -p httpdate --precise=1.0.2
          cargo test
          cargo test --features "json-using-serde proxy punycode"
